import type { Metadata } from "next"
import { Poppins, Unbounded } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/app/navbar"
import Footer from "@/components/app/footer"

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
})

const unbounded = Unbounded({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-unbounded",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Harmony Website",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${poppins.variable} 
          ${unbounded.variable} 
          antialiased
        `}
      >
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
